apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: retail-store
  source:
<<<<<<< HEAD
    repoURL: https://github.com/LondheShubham153/retail-store-sample-app
    targetRevision: main
=======
    repoURL: https://github.com/sagarjaiswal945/retail-store-sample-app
    targetRevision: gitops
>>>>>>> c833a27cd100bbb9de5eb152abd59fb36e1a291c
    path: src/ui/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
